/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.user.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.miso4204.user.logic.dto.UserDTO;
import co.edu.uniandes.csw.miso4204.user.logic.dto.UserPageDTO;
import co.edu.uniandes.csw.miso4204.user.logic.api._IUserLogicService;

public abstract class _UserMockLogicService implements _IUserLogicService {

	private Long id= new Long(1);
	protected List<UserDTO> data=new ArrayList<UserDTO>();

	public UserDTO createUser(UserDTO user){
		id++;
		user.setId(id);
		data.add(user);
		return user;
    }
    
    public List<UserDTO> getUsers(){
		return data; 
	}

	public UserPageDTO getUsers(Integer page, Integer maxRecords){
		UserPageDTO response = new UserPageDTO();
		response.setTotalRecords(Long.parseLong(data.size()+""));
		response.setRecords(data);
		return response;
	}

	public UserDTO getUser(Long id){
		for(UserDTO data1:data){
			if(data1.getId().equals(id)){
				return data1;
			}
		}
		return null;
	}

	public void deleteUser(Long id){
	    UserDTO delete=null;
		for(UserDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
		} 
	}

	public void updateUser(UserDTO user){
	    UserDTO delete=null;
		for(UserDTO data1:data){
			if(data1.getId().equals(user.getId())){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
			data.add(user);
		} 
	}	
}