/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.paymentmode.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.miso4204.paymentmode.logic.dto.PaymentModeDTO;
import co.edu.uniandes.csw.miso4204.paymentmode.logic.dto.PaymentModePageDTO;
import co.edu.uniandes.csw.miso4204.paymentmode.logic.api._IPaymentModeLogicService;

public abstract class _PaymentModeMockLogicService implements _IPaymentModeLogicService {

	private Long id= new Long(1);
	protected List<PaymentModeDTO> data=new ArrayList<PaymentModeDTO>();

	public PaymentModeDTO createPaymentMode(PaymentModeDTO paymentMode){
		id++;
		paymentMode.setId(id);
		data.add(paymentMode);
		return paymentMode;
    }
    
    public List<PaymentModeDTO> getPaymentModes(){
		return data; 
	}

	public PaymentModePageDTO getPaymentModes(Integer page, Integer maxRecords){
		PaymentModePageDTO response = new PaymentModePageDTO();
		response.setTotalRecords(Long.parseLong(data.size()+""));
		response.setRecords(data);
		return response;
	}

	public PaymentModeDTO getPaymentMode(Long id){
		for(PaymentModeDTO data1:data){
			if(data1.getId().equals(id)){
				return data1;
			}
		}
		return null;
	}

	public void deletePaymentMode(Long id){
	    PaymentModeDTO delete=null;
		for(PaymentModeDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
		} 
	}

	public void updatePaymentMode(PaymentModeDTO paymentMode){
	    PaymentModeDTO delete=null;
		for(PaymentModeDTO data1:data){
			if(data1.getId().equals(paymentMode.getId())){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
			data.add(paymentMode);
		} 
	}	
}