/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.shoppingcart.master.logic.dto;

import co.edu.uniandes.csw.miso4204.shoppingcartitem.logic.dto.ShoppingCartItemDTO;
import co.edu.uniandes.csw.miso4204.shoppingcart.logic.dto.ShoppingCartDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _ShoppingCartMasterDTO {

 
    protected ShoppingCartDTO shoppingcartEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public ShoppingCartDTO getShoppingCartEntity() {
        return shoppingcartEntity;
    }

    public void setShoppingCartEntity(ShoppingCartDTO shoppingcartEntity) {
        this.shoppingcartEntity = shoppingcartEntity;
    }
    
    public List<ShoppingCartItemDTO> createshoppingCartItem;
    public List<ShoppingCartItemDTO> updateshoppingCartItem;
    public List<ShoppingCartItemDTO> deleteshoppingCartItem;
    public List<ShoppingCartItemDTO> listshoppingCartItem;	
	
	
	
    public List<ShoppingCartItemDTO> getCreateshoppingCartItem(){ return createshoppingCartItem; };
    public void setCreateshoppingCartItem(List<ShoppingCartItemDTO> createshoppingCartItem){ this.createshoppingCartItem=createshoppingCartItem; };
    public List<ShoppingCartItemDTO> getUpdateshoppingCartItem(){ return updateshoppingCartItem; };
    public void setUpdateshoppingCartItem(List<ShoppingCartItemDTO> updateshoppingCartItem){ this.updateshoppingCartItem=updateshoppingCartItem; };
    public List<ShoppingCartItemDTO> getDeleteshoppingCartItem(){ return deleteshoppingCartItem; };
    public void setDeleteshoppingCartItem(List<ShoppingCartItemDTO> deleteshoppingCartItem){ this.deleteshoppingCartItem=deleteshoppingCartItem; };
    public List<ShoppingCartItemDTO> getListshoppingCartItem(){ return listshoppingCartItem; };
    public void setListshoppingCartItem(List<ShoppingCartItemDTO> listshoppingCartItem){ this.listshoppingCartItem=listshoppingCartItem; };	
	
	
}

