/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.wishlist.master.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.miso4204.wishlist.logic.dto.WishListDTO;
import co.edu.uniandes.csw.miso4204.wishlist.logic.api.IWishListLogicService;
import co.edu.uniandes.csw.miso4204.wishlist.master.logic.api._IWishListMasterLogicService;
import co.edu.uniandes.csw.miso4204.wishlist.master.logic.dto.WishListMasterDTO;
import co.edu.uniandes.csw.miso4204.wishlistitem.logic.api.IWishListItemLogicService;
import co.edu.uniandes.csw.miso4204.wishlistitem.logic.dto.WishListItemDTO;
import javax.inject.Inject;
import javax.ejb.EJB;


public abstract class _WishListMasterMockLogicService implements _IWishListMasterLogicService {

    protected static ArrayList<WishListMasterDTO> wishListMasterDtosList = new ArrayList<WishListMasterDTO>() ;
    @Inject
    protected IWishListItemLogicService wishListItemPersistance;
    @Inject
    protected IWishListLogicService wishListPersistance;

    public WishListMasterDTO createMasterWishList(WishListMasterDTO wishList) {

        wishListPersistance.createWishList(wishList.getWishListEntity());
        for (WishListItemDTO dto : wishList.getCreatewhishListItem()) {
            wishList.getListwhishListItem().add(wishListItemPersistance.createWishListItem(dto));
        }
        wishListMasterDtosList.add(wishList);
        return wishList;
    }

    public WishListMasterDTO getMasterWishList(Long id) {
        for (WishListMasterDTO wishListMasterDTO : wishListMasterDtosList) {
            if (wishListMasterDTO.getWishListEntity().getId() == id) {
                return wishListMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterWishList(Long id) {
        for (WishListMasterDTO wishListMasterDTO : wishListMasterDtosList) {
            if (wishListMasterDTO.getWishListEntity().getId() == id) {

                for (WishListItemDTO dto : wishListMasterDTO.getCreatewhishListItem()) {
                    wishListItemPersistance.deleteWishListItem(dto.getId());
                }
                wishListPersistance.deleteWishList(wishListMasterDTO.getId());
                wishListMasterDtosList.remove(wishListMasterDTO);
            }
        }

    }

    public void updateMasterWishList(WishListMasterDTO wishList) {

		WishListMasterDTO currentWishList = getMasterWishList(wishList.getWishListEntity().getId());
		if (currentWishList == null) {
			currentWishList = wishList;
		}else{
			wishListMasterDtosList.remove(currentWishList);
		}

        // update WishListItem
        if (wishList.getUpdatewhishListItem() != null) {
            for (WishListItemDTO dto : wishList.getUpdatewhishListItem()) {
                wishListItemPersistance.updateWishListItem(dto);
                for (WishListItemDTO wishListItemdto : currentWishList.getListwhishListItem()) {
					if (wishListItemdto.getId() == dto.getId()) {
						currentWishList.getListwhishListItem().remove(wishListItemdto);
						currentWishList.getListwhishListItem().add(dto);
					}
				}
            }
        }
        // persist new WishListItem
        if (wishList.getCreatewhishListItem() != null) {
            for (WishListItemDTO dto : wishList.getCreatewhishListItem()) {
                WishListItemDTO persistedWishListItemDTO = wishListItemPersistance.createWishListItem(dto);
                dto = persistedWishListItemDTO;
                currentWishList.getListwhishListItem().add(dto);
            }
        }
        // delete WishListItem
        if (wishList.getDeletewhishListItem() != null) {
            for (WishListItemDTO dto : wishList.getDeletewhishListItem()) {
				for (WishListItemDTO wishListItemdto : currentWishList.getListwhishListItem()) {
					if (wishListItemdto.getId() == dto.getId()) {
						currentWishList.getListwhishListItem().remove(wishListItemdto);
					}
				}
                wishListItemPersistance.deleteWishListItem(dto.getId());
            }
        }
        wishListMasterDtosList.add(currentWishList);
    }
}