/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.creditcard.logic.dto;

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement 
public abstract class _CreditCardDTO {

	

	private Integer cardNumber;
	

	private String expirationDate;
	

	private Integer cvc;
	

	private Long id;
	

	private String name;
	

	private String branch;
	

	private String accountType;



	public Integer getCardNumber() {
		return cardNumber;
	}
 
	public void setCardNumber(Integer cardnumber) {
		this.cardNumber = cardnumber;
	}


	public String getExpirationDate() {
		return expirationDate;
	}
 
	public void setExpirationDate(String expirationdate) {
		this.expirationDate = expirationdate;
	}


	public Integer getCvc() {
		return cvc;
	}
 
	public void setCvc(Integer cvc) {
		this.cvc = cvc;
	}


	public Long getId() {
		return id;
	}
 
	public void setId(Long id) {
		this.id = id;
	}


	public String getName() {
		return name;
	}
 
	public void setName(String name) {
		this.name = name;
	}


	public String getBranch() {
		return branch;
	}
 
	public void setBranch(String branch) {
		this.branch = branch;
	}


	public String getAccountType() {
		return accountType;
	}
 
	public void setAccountType(String accounttype) {
		this.accountType = accounttype;
	}
	
}