/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.shoppingcart.master.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.miso4204.shoppingcart.logic.dto.ShoppingCartDTO;
import co.edu.uniandes.csw.miso4204.shoppingcart.logic.api.IShoppingCartLogicService;
import co.edu.uniandes.csw.miso4204.shoppingcart.master.logic.api._IShoppingCartMasterLogicService;
import co.edu.uniandes.csw.miso4204.shoppingcart.master.logic.dto.ShoppingCartMasterDTO;
import co.edu.uniandes.csw.miso4204.shoppingcartitem.logic.api.IShoppingCartItemLogicService;
import co.edu.uniandes.csw.miso4204.shoppingcartitem.logic.dto.ShoppingCartItemDTO;
import javax.inject.Inject;
import javax.ejb.EJB;


public abstract class _ShoppingCartMasterMockLogicService implements _IShoppingCartMasterLogicService {

    protected static ArrayList<ShoppingCartMasterDTO> shoppingCartMasterDtosList = new ArrayList<ShoppingCartMasterDTO>() ;
    @Inject
    protected IShoppingCartItemLogicService shoppingCartItemPersistance;
    @Inject
    protected IShoppingCartLogicService shoppingCartPersistance;

    public ShoppingCartMasterDTO createMasterShoppingCart(ShoppingCartMasterDTO shoppingCart) {

        shoppingCartPersistance.createShoppingCart(shoppingCart.getShoppingCartEntity());
        for (ShoppingCartItemDTO dto : shoppingCart.getCreateshoppingCartItem()) {
            shoppingCart.getListshoppingCartItem().add(shoppingCartItemPersistance.createShoppingCartItem(dto));
        }
        shoppingCartMasterDtosList.add(shoppingCart);
        return shoppingCart;
    }

    public ShoppingCartMasterDTO getMasterShoppingCart(Long id) {
        for (ShoppingCartMasterDTO shoppingCartMasterDTO : shoppingCartMasterDtosList) {
            if (shoppingCartMasterDTO.getShoppingCartEntity().getId() == id) {
                return shoppingCartMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterShoppingCart(Long id) {
        for (ShoppingCartMasterDTO shoppingCartMasterDTO : shoppingCartMasterDtosList) {
            if (shoppingCartMasterDTO.getShoppingCartEntity().getId() == id) {

                for (ShoppingCartItemDTO dto : shoppingCartMasterDTO.getCreateshoppingCartItem()) {
                    shoppingCartItemPersistance.deleteShoppingCartItem(dto.getId());
                }
                shoppingCartPersistance.deleteShoppingCart(shoppingCartMasterDTO.getId());
                shoppingCartMasterDtosList.remove(shoppingCartMasterDTO);
            }
        }

    }

    public void updateMasterShoppingCart(ShoppingCartMasterDTO shoppingCart) {

		ShoppingCartMasterDTO currentShoppingCart = getMasterShoppingCart(shoppingCart.getShoppingCartEntity().getId());
		if (currentShoppingCart == null) {
			currentShoppingCart = shoppingCart;
		}else{
			shoppingCartMasterDtosList.remove(currentShoppingCart);
		}

        // update ShoppingCartItem
        if (shoppingCart.getUpdateshoppingCartItem() != null) {
            for (ShoppingCartItemDTO dto : shoppingCart.getUpdateshoppingCartItem()) {
                shoppingCartItemPersistance.updateShoppingCartItem(dto);
                for (ShoppingCartItemDTO shoppingCartItemdto : currentShoppingCart.getListshoppingCartItem()) {
					if (shoppingCartItemdto.getId() == dto.getId()) {
						currentShoppingCart.getListshoppingCartItem().remove(shoppingCartItemdto);
						currentShoppingCart.getListshoppingCartItem().add(dto);
					}
				}
            }
        }
        // persist new ShoppingCartItem
        if (shoppingCart.getCreateshoppingCartItem() != null) {
            for (ShoppingCartItemDTO dto : shoppingCart.getCreateshoppingCartItem()) {
                ShoppingCartItemDTO persistedShoppingCartItemDTO = shoppingCartItemPersistance.createShoppingCartItem(dto);
                dto = persistedShoppingCartItemDTO;
                currentShoppingCart.getListshoppingCartItem().add(dto);
            }
        }
        // delete ShoppingCartItem
        if (shoppingCart.getDeleteshoppingCartItem() != null) {
            for (ShoppingCartItemDTO dto : shoppingCart.getDeleteshoppingCartItem()) {
				for (ShoppingCartItemDTO shoppingCartItemdto : currentShoppingCart.getListshoppingCartItem()) {
					if (shoppingCartItemdto.getId() == dto.getId()) {
						currentShoppingCart.getListshoppingCartItem().remove(shoppingCartItemdto);
					}
				}
                shoppingCartItemPersistance.deleteShoppingCartItem(dto.getId());
            }
        }
        shoppingCartMasterDtosList.add(currentShoppingCart);
    }
}