/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.feature.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.miso4204.feature.logic.dto.FeatureDTO;
import co.edu.uniandes.csw.miso4204.feature.logic.dto.FeaturePageDTO;
import co.edu.uniandes.csw.miso4204.feature.logic.api._IFeatureLogicService;

public abstract class _FeatureMockLogicService implements _IFeatureLogicService {

	private Long id= new Long(1);
	protected List<FeatureDTO> data=new ArrayList<FeatureDTO>();

	public FeatureDTO createFeature(FeatureDTO feature){
		id++;
		feature.setId(id);
		data.add(feature);
		return feature;
    }
    
    public List<FeatureDTO> getFeatures(){
		return data; 
	}

	public FeaturePageDTO getFeatures(Integer page, Integer maxRecords){
		FeaturePageDTO response = new FeaturePageDTO();
		response.setTotalRecords(Long.parseLong(data.size()+""));
		response.setRecords(data);
		return response;
	}

	public FeatureDTO getFeature(Long id){
		for(FeatureDTO data1:data){
			if(data1.getId().equals(id)){
				return data1;
			}
		}
		return null;
	}

	public void deleteFeature(Long id){
	    FeatureDTO delete=null;
		for(FeatureDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
		} 
	}

	public void updateFeature(FeatureDTO feature){
	    FeatureDTO delete=null;
		for(FeatureDTO data1:data){
			if(data1.getId().equals(feature.getId())){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
			data.add(feature);
		} 
	}	
}