/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.purchase.master.logic.dto;

import co.edu.uniandes.csw.miso4204.purchaseitem.logic.dto.PurchaseItemDTO;
import co.edu.uniandes.csw.miso4204.payment.logic.dto.PaymentDTO;
import co.edu.uniandes.csw.miso4204.purchase.logic.dto.PurchaseDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _PurchaseMasterDTO {

 
    protected PurchaseDTO purchaseEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public PurchaseDTO getPurchaseEntity() {
        return purchaseEntity;
    }

    public void setPurchaseEntity(PurchaseDTO purchaseEntity) {
        this.purchaseEntity = purchaseEntity;
    }
    
    public List<PurchaseItemDTO> createpurchaseItem;
    public List<PurchaseItemDTO> updatepurchaseItem;
    public List<PurchaseItemDTO> deletepurchaseItem;
    public List<PurchaseItemDTO> listpurchaseItem;	
    public List<PaymentDTO> createpayment;
    public List<PaymentDTO> updatepayment;
    public List<PaymentDTO> deletepayment;
    public List<PaymentDTO> listpayment;	
	
	
	
    public List<PurchaseItemDTO> getCreatepurchaseItem(){ return createpurchaseItem; };
    public void setCreatepurchaseItem(List<PurchaseItemDTO> createpurchaseItem){ this.createpurchaseItem=createpurchaseItem; };
    public List<PurchaseItemDTO> getUpdatepurchaseItem(){ return updatepurchaseItem; };
    public void setUpdatepurchaseItem(List<PurchaseItemDTO> updatepurchaseItem){ this.updatepurchaseItem=updatepurchaseItem; };
    public List<PurchaseItemDTO> getDeletepurchaseItem(){ return deletepurchaseItem; };
    public void setDeletepurchaseItem(List<PurchaseItemDTO> deletepurchaseItem){ this.deletepurchaseItem=deletepurchaseItem; };
    public List<PurchaseItemDTO> getListpurchaseItem(){ return listpurchaseItem; };
    public void setListpurchaseItem(List<PurchaseItemDTO> listpurchaseItem){ this.listpurchaseItem=listpurchaseItem; };	
    public List<PaymentDTO> getCreatepayment(){ return createpayment; };
    public void setCreatepayment(List<PaymentDTO> createpayment){ this.createpayment=createpayment; };
    public List<PaymentDTO> getUpdatepayment(){ return updatepayment; };
    public void setUpdatepayment(List<PaymentDTO> updatepayment){ this.updatepayment=updatepayment; };
    public List<PaymentDTO> getDeletepayment(){ return deletepayment; };
    public void setDeletepayment(List<PaymentDTO> deletepayment){ this.deletepayment=deletepayment; };
    public List<PaymentDTO> getListpayment(){ return listpayment; };
    public void setListpayment(List<PaymentDTO> listpayment){ this.listpayment=listpayment; };	
	
	
}

