/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.creditcard.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.miso4204.creditcard.logic.dto.CreditCardDTO;
import co.edu.uniandes.csw.miso4204.creditcard.logic.dto.CreditCardPageDTO;
import co.edu.uniandes.csw.miso4204.creditcard.logic.api._ICreditCardLogicService;

public abstract class _CreditCardMockLogicService implements _ICreditCardLogicService {

	private Long id= new Long(1);
	protected List<CreditCardDTO> data=new ArrayList<CreditCardDTO>();

	public CreditCardDTO createCreditCard(CreditCardDTO creditCard){
		id++;
		creditCard.setId(id);
		data.add(creditCard);
		return creditCard;
    }
    
    public List<CreditCardDTO> getCreditCards(){
		return data; 
	}

	public CreditCardPageDTO getCreditCards(Integer page, Integer maxRecords){
		CreditCardPageDTO response = new CreditCardPageDTO();
		response.setTotalRecords(Long.parseLong(data.size()+""));
		response.setRecords(data);
		return response;
	}

	public CreditCardDTO getCreditCard(Long id){
		for(CreditCardDTO data1:data){
			if(data1.getId().equals(id)){
				return data1;
			}
		}
		return null;
	}

	public void deleteCreditCard(Long id){
	    CreditCardDTO delete=null;
		for(CreditCardDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
		} 
	}

	public void updateCreditCard(CreditCardDTO creditCard){
	    CreditCardDTO delete=null;
		for(CreditCardDTO data1:data){
			if(data1.getId().equals(creditCard.getId())){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
			data.add(creditCard);
		} 
	}	
}