/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.shoppingcartitem.service;

import java.util.List;

import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.QueryParam;
import javax.inject.Inject;

import co.edu.uniandes.csw.miso4204.shoppingcartitem.logic.api.IShoppingCartItemLogicService;
import co.edu.uniandes.csw.miso4204.shoppingcartitem.logic.dto.ShoppingCartItemDTO;
import co.edu.uniandes.csw.miso4204.shoppingcartitem.logic.dto.ShoppingCartItemPageDTO;


public abstract class _ShoppingCartItemService {

	@Inject
	protected IShoppingCartItemLogicService shoppingCartItemLogicService;
	
	@POST
	public ShoppingCartItemDTO createShoppingCartItem(ShoppingCartItemDTO shoppingCartItem){
		return shoppingCartItemLogicService.createShoppingCartItem(shoppingCartItem);
	}
	
	@DELETE
	@Path("{id}")
	public void deleteShoppingCartItem(@PathParam("id") Long id){
		shoppingCartItemLogicService.deleteShoppingCartItem(id);
	}
	
	@GET
	public ShoppingCartItemPageDTO getShoppingCartItems(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords){
		return shoppingCartItemLogicService.getShoppingCartItems(page, maxRecords);
	}
	
	@GET
	@Path("{id}")
	public ShoppingCartItemDTO getShoppingCartItem(@PathParam("id") Long id){
		return shoppingCartItemLogicService.getShoppingCartItem(id);
	}
	
	@PUT
	public void updateShoppingCartItem(@PathParam("id") Long id, ShoppingCartItemDTO shoppingCartItem){
		shoppingCartItemLogicService.updateShoppingCartItem(shoppingCartItem);
	}
	
}