/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.product.master.logic.dto;

import co.edu.uniandes.csw.miso4204.picture.logic.dto.PictureDTO;
import co.edu.uniandes.csw.miso4204.feature.logic.dto.FeatureDTO;
import co.edu.uniandes.csw.miso4204.product.logic.dto.ProductDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _ProductMasterDTO {

 
    protected ProductDTO productEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public ProductDTO getProductEntity() {
        return productEntity;
    }

    public void setProductEntity(ProductDTO productEntity) {
        this.productEntity = productEntity;
    }
    
    public List<PictureDTO> createpicture;
    public List<PictureDTO> updatepicture;
    public List<PictureDTO> deletepicture;
    public List<PictureDTO> listpicture;	
    public List<FeatureDTO> createfeature;
    public List<FeatureDTO> updatefeature;
    public List<FeatureDTO> deletefeature;
    public List<FeatureDTO> listfeature;	
	
	
	
    public List<PictureDTO> getCreatepicture(){ return createpicture; };
    public void setCreatepicture(List<PictureDTO> createpicture){ this.createpicture=createpicture; };
    public List<PictureDTO> getUpdatepicture(){ return updatepicture; };
    public void setUpdatepicture(List<PictureDTO> updatepicture){ this.updatepicture=updatepicture; };
    public List<PictureDTO> getDeletepicture(){ return deletepicture; };
    public void setDeletepicture(List<PictureDTO> deletepicture){ this.deletepicture=deletepicture; };
    public List<PictureDTO> getListpicture(){ return listpicture; };
    public void setListpicture(List<PictureDTO> listpicture){ this.listpicture=listpicture; };	
    public List<FeatureDTO> getCreatefeature(){ return createfeature; };
    public void setCreatefeature(List<FeatureDTO> createfeature){ this.createfeature=createfeature; };
    public List<FeatureDTO> getUpdatefeature(){ return updatefeature; };
    public void setUpdatefeature(List<FeatureDTO> updatefeature){ this.updatefeature=updatefeature; };
    public List<FeatureDTO> getDeletefeature(){ return deletefeature; };
    public void setDeletefeature(List<FeatureDTO> deletefeature){ this.deletefeature=deletefeature; };
    public List<FeatureDTO> getListfeature(){ return listfeature; };
    public void setListfeature(List<FeatureDTO> listfeature){ this.listfeature=listfeature; };	
	
	
}

