/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.purchase.logic.dto;

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement 
public abstract class _PurchaseDTO {

	

	private Long id;
	

	private String name;
	

	private String purchaseDate;
	

	private Double totalValue;
	

	private Integer totalItems;
	

	private Integer points;
	

	private Long buyerId;
	

	private Long addressId;



	public Long getId() {
		return id;
	}
 
	public void setId(Long id) {
		this.id = id;
	}


	public String getName() {
		return name;
	}
 
	public void setName(String name) {
		this.name = name;
	}


	public String getPurchaseDate() {
		return purchaseDate;
	}
 
	public void setPurchaseDate(String purchasedate) {
		this.purchaseDate = purchasedate;
	}


	public Double getTotalValue() {
		return totalValue;
	}
 
	public void setTotalValue(Double totalvalue) {
		this.totalValue = totalvalue;
	}


	public Integer getTotalItems() {
		return totalItems;
	}
 
	public void setTotalItems(Integer totalitems) {
		this.totalItems = totalitems;
	}


	public Integer getPoints() {
		return points;
	}
 
	public void setPoints(Integer points) {
		this.points = points;
	}


	public Long getBuyerId() {
		return buyerId;
	}
 
	public void setBuyerId(Long buyerid) {
		this.buyerId = buyerid;
	}


	public Long getAddressId() {
		return addressId;
	}
 
	public void setAddressId(Long addressid) {
		this.addressId = addressid;
	}
	
}