/* ========================================================================
 * Copyright 2014 miso4204
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 miso4204

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.miso4204.user.service;

import java.util.List;

import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.QueryParam;
import javax.inject.Inject;

import co.edu.uniandes.csw.miso4204.user.logic.api.IUserLogicService;
import co.edu.uniandes.csw.miso4204.user.logic.dto.UserDTO;
import co.edu.uniandes.csw.miso4204.user.logic.dto.UserPageDTO;


public abstract class _UserService {

	@Inject
	protected IUserLogicService userLogicService;
	
	@POST
	public UserDTO createUser(UserDTO user){
		return userLogicService.createUser(user);
	}
	
	@DELETE
	@Path("{id}")
	public void deleteUser(@PathParam("id") Long id){
		userLogicService.deleteUser(id);
	}
	
	@GET
	public UserPageDTO getUsers(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords){
		return userLogicService.getUsers(page, maxRecords);
	}
	
	@GET
	@Path("{id}")
	public UserDTO getUser(@PathParam("id") Long id){
		return userLogicService.getUser(id);
	}
	
	@PUT
	public void updateUser(@PathParam("id") Long id, UserDTO user){
		userLogicService.updateUser(user);
	}
	
}